import type { CSSProperties } from 'react';

export const homeStyles: { [key: string]: CSSProperties } = {
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '0 20px',
  },
  homePage: {
    width: '100%',
  },
  hero: {
    background: 'linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), url("/homepage.jpg") center/cover no-repeat',
    height: '70vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    color: 'white',
  },
  heroContent: {
    maxWidth: '800px',
  },
  heroTitle: {
    fontSize: '3.5rem',
    fontWeight: 'bold',
    margin: 0,
    textShadow: '2px 2px 4px rgba(0, 0, 0, 0.5)',
  },
  heroSubtitle: {
    fontSize: '2rem',
    fontWeight: 'normal',
    opacity: 0.9,
  },
  howItWorks: {
    padding: '5rem 0',
    background: '#f8f9fa',
  },
  sectionTitle: {
    textAlign: 'center',
    fontSize: '2.5rem',
    fontWeight: 'bold',
    color: '#333',
    margin: '0 0 1rem 0',
  },
  sectionSubtitle: {
    textAlign: 'center',
    color: '#666',
    fontSize: '1.1rem',
    margin: '0 0 3rem 0',
    lineHeight: 1.6,
  },
  stepsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '2rem',
    maxWidth: '1000px',
    margin: '0 auto',
  },
  stepCard: {
    background: 'white',
    padding: '2rem',
    borderRadius: '12px',
    textAlign: 'center',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
    transition: 'transform 0.3s ease',
  },
  stepCardHover: {
    background: 'white',
    padding: '2rem',
    borderRadius: '12px',
    textAlign: 'center',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
    transition: 'transform 0.3s ease',
    transform: 'translateY(-5px)',
  },
  stepIcon: {
    marginBottom: '1.5rem',
  },
  iconCircle1: {
    width: '80px',
    height: '80px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #ff6b6b, #ee5a6f)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto',
  },
  iconCircle2: {
    width: '80px',
    height: '80px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #4ecdc4, #44a08d)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto',
  },
  iconCircle3: {
    width: '80px',
    height: '80px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #45b7d1, #96c93d)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto',
  },
  icon: {
    fontSize: '2rem',
    color: 'white',
  },
  stepTitle: {
    fontSize: '1.3rem',
    fontWeight: 'bold',
    color: '#333',
    margin: '0 0 1rem 0',
  },
  stepDescription: {
    color: '#666',
    lineHeight: 1.6,
    margin: 0,
  },
  upcomingMeetup: {
    padding: '3rem 0',
    background: 'white',
  },
  meetupCard: {
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    borderRadius: '16px',
    padding: '2rem',
    color: 'white',
    maxWidth: '800px',
    margin: '0 auto',
    position: 'relative',
  },
  meetupContent: {
    display: 'flex',
    alignItems: 'center',
    gap: '1.5rem',
  },
  meetupIcon: {
    fontSize: '2.5rem',
    background: 'rgba(255, 255, 255, 0.2)',
    padding: '1rem',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '60px',
    height: '60px',
  },
  meetupTitle: {
    fontSize: '1.5rem',
    fontWeight: 'bold',
    margin: '0 0 0.5rem 0',
  },
  meetupInfo: {
    margin: '0 0 1rem 0',
    opacity: 0.9,
  },
  joinEventBtn: {
    background: 'white',
    color: '#667eea',
    border: 'none',
    padding: '0.7rem 1.5rem',
    borderRadius: '6px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s ease',
  },
  joinEventBtnHover: {
    background: '#f0f0f0',
    color: '#667eea',
    border: 'none',
    padding: '0.7rem 1.5rem',
    borderRadius: '6px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s ease',
  },
  meetupDots: {
    display: 'flex',
    justifyContent: 'center',
    gap: '0.5rem',
    marginTop: '1.5rem',
  },
  dot: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    background: 'rgba(255, 255, 255, 0.3)',
    transition: 'all 0.3s ease',
  },
  dotActive: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    background: 'white',
    transition: 'all 0.3s ease',
  },
}; 